using System;

namespace Yort.Zip.InStore
{
	/// <summary>
	/// Provides details of a successful refund created by <see cref="IZipClient.RefundOrderAsync(RefundOrderRequest)"/>.
	/// </summary>
	public class RefundOrderResponse
	{
		/// <summary>
		/// A unique refund id generated by Zip.
		/// </summary>
		public string Id { get; set; } = null!;

		/// <summary>
		/// The UTC timestamp when the refund was processed.
		/// </summary>
		public DateTimeOffset? RefundedDateTime { get; set; } = null;

		/// <summary>
		/// The merchant reference for this refund as specified in <see cref="RefundOrderRequest.MerchantRefundReference"/>.
		/// </summary>
		public string MerchantReference { get; set; } = null!;

		/// <summary>
		/// The amount refunded.
		/// </summary>
		public decimal Amount { get; set; }
	}
}
